title: "Robert W. Maness"
description: "IAM Engineer"
background: "/assets/img/astronaut.png"

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-remote-theme

custom_css: /assets/css/custom.css
favicon: /favicon.ico

markdown: kramdown

collections:
  recipes:
    output: true
    permalink: /cooking/:name/
  iam:
    output: true
    permalink: /iam/:name/
