title: "Robert W. Maness"
description: "Thoughts and musings."

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

markdown: kramdown
#
collections:
  thoughts:
    output: true
    permalink: /thoughts/:name/
  recipes:
    output: true
    permalink: /recipes/:name/


defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: page
  - scope:
      path: ""
      type: thoughts
    values:
      layout: page
      
header_pages:
  - recipes.md
  - thoughts.md

navbar-links:
  Home: "/"
  Recipes: "/recipes/"
  Sermons: "/sermons/"
  Writing: "/posts/"
