title: "Robert W. Maness"
description: "A few musings on theology, cybersecurity, books, and cooking."
background: "/assets/img/batman.webp"

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-remote-theme

custom_css: /assets/css/custom.css

markdown: kramdown

collections:
  recipes:
    output: true
    permalink: /cooking/:name/
  iam:
    output: true
    permalink: /iam/:name/
