title: "Robert W. Maness"
description: "Thoughts and musings."
theme: chirpy
markdown: kramdown

collections:
  thoughts:
    output: true
    permalink: /thoughts/:name/
  recipes:
    output: true
    permalink: /recipes/:name/


defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: page
  - scope:
      path: ""
      type: thoughts
    values:
      layout: page
      
header_pages:
  - recipes.md
  - thoughts.md
